export  const homeObjOne = {
    id: 'expertise',
    lightBg: false,
    lightText: true,
    lightTextDesc: false,
    script: false,
    big: false,
    topLine: '',
    headLine2:'',
    headLine: 'Our Expertise',
    description: 'CEO Inc. is an award-winning, full-service, direct-hire search firm, that for over 27 years has specialized in direct hire placement for companies in several markets across the country.',
    imgStart: false,
    img: require('../../images/team.png'),
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: true,
    short: true,
    slides1: true,
    isimg: false
}
export  const homeObjTwo = {
    id: 'spotlight',
    lightBg: false,
    lightText: true,
    lightTextDesc: false,
    script: true,
    big: true,
    topLine: '',
    headLine: 'spotloght',
    description: '"Delivering top talent nationally for over 27 years"',
    imgStart: true,
    img: require('../../images/team.png'),
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: true,
    short:false,
    slides1: false,
    isimg: true
}

